result = None
       try
            self.fail("Oops")
        except StandardError as ex:
            result = 'exception handled'
